### ISSUE TITLE
Request for ElectronJS Compatibility Assistance

### ISSUE THREAD

**Issue by SnRoma5** [rhahao/jw-epub-parser#296]
Dear @rhahao,

I hope this message finds you well. I've been a long-time user of your npm package, and I truly appreciate the work you've put into it!

However, I'm currently facing a challenge. I'm working on an ElectronJS application, and it appears that my App does not support ES6, which is causing compatibility issues within your package. 

In earlier versions of your package (v. 1.36.0), I was able to make some adjustments to integrate it seamlessly into my projects (jw-epub-parser\dist\node\index.js). However, the recent changes have made it more difficult for me to use your package within my ElectronJS application. I've tried to make the necessary modifications myself, but I'm encountering difficulties.

I'm wondering if you could assist me in adapting the package for use in ElectronJS without ES6 support. I would be more than happy to provide you with the script that has been working for me so far, as well as specific details about the issues I've encountered:
[index.zip](https://github.com/rhahao/jw-epub-parser/files/13285174/index.zip)

Your expertise and support in this matter would be greatly appreciated, as it would enable me to continue using your package in my ElectronJS project. It's worth mentioning that I only need the package to parse the Epub file of the workbook. Maybe you could send me a simplified version that supports the new workbooks 2024. 

Please let me know if you're available to work on this and if you require any additional information from my end.

Thank you for your time and consideration. I look forward to your response.

Best regards

**Comment by rhahao** [comment]
Hello @SnRoma5! Thanks for reaching out and I hope you are doing well too! 😄

I would be very to help and to make any needed adjustment to make the package works for your use case. But for sure, I will need additional information to know what exactly is the problem on your side. Together, may be we will be able to pinpoint the changes that I’ve made that breaks it on your side.

Greetings!

**Comment by rhahao** [comment]
Meanwhile, I’ve prepared a `cjs` output of the package. I do not know if it makes any difference.
[index.cjs.zip](https://github.com/rhahao/jw-epub-parser/files/13285281/index.cjs.zip)

**Comment by SnRoma5** [comment]
Thank you very much for your help. I really appreciate it!!!

I have inserted the files under node_modules\jw-epub-parser\dist\node.

This is how I import your package into my application:
const jwparser = require('jw-epub-parser/dist/node/index.cjs.js')

But I get this error when I try to start the application:

Error: Cannot find module 'global-jsdom/register'
Require stack:

The same happens with the other packages you import:
require("global-jsdom/register");
var e = require("node-fetch"),
t = require("fs/promises"),
r = require("fileformat"),

In an earlier version of your package, I simply commented out these packages. This then worked:
//import 'global-jsdom/register';
//import JSZip from 'jszip';
//import fetch from 'node-fetch';
//import * as fs from 'fs';
//import * as path from 'path';
//import dateFormat from 'dateformat';

const JSZip = require('jszip');
const fs = require('fs');
const path = require('path');


But if I do the same now, I get an error message:
"use strict."
//require("global-jsdom/register");
//var e = require("node-fetch"),
var a = require("path"),
    //t = require("fs/promises"),
    //r = require("fileformat"),
    i = require("jszip"),
    o = require("node-html-parser");

Error:
App threw an error during load
ReferenceError: window is not defined

**Comment by SnRoma5** [comment]
These are my notes that I made so that I don't forget what I changed in your code version 1.36.0. Maybe this will help you.
I am not an experienced developer. So thank you for your patience!

index.node.js must be adapted. Instead of import you have to use require:
    ORIGINAL:
        import 'global-jsdom/register';
        import JSZip from 'jszip';
        import fetch from 'node-fetch';
        import * as fs from 'fs';
        import * as path from 'path';
        import dateFormat from 'dateformat';
    CHANGES:
        const JSZip = require('jszip');
        const fs = require('fs');
        const path = require('path');

   You must also replace:
    ORIGINAL: 
        export { loadEPUB };
    CHANGES:
        module.exports = loadEPUB;

**Comment by rhahao** [comment]
Thanks for these additional info. I will look at them and come back to you asap.

**Comment by rhahao** [comment]
> Error:
> App threw an error during load
> ReferenceError: window is not defined

@SnRoma5: did you receive the same error when you use the current released version and the cjs output file I provided above?

**Comment by SnRoma5** [comment]
Exactly. The current released version does not work because the import statement is written in ES6 and electronJS does not support ES6. 

I get this error:

import*as e from"path-browserify";import r from"dateformat";import t from"jszip";var a={januaryVariations:"January",februaryVariations:"February",marchVariations:"March",aprilVariations:"April",mayVariations:"May",juneVariations:"June",julyVariations:"July",augustVariations:"August",septemberVariations:"September",octoberVariations:"October",novemberVariations:"November",decemberVariations:"December",tgwTalk10Variations:"{{ title }}: (10 min.)",tgwBibleReadingVariations:"Bible Reading: (4 min.) 
{{ source }}",initialCallVideoVariations:"Initial Call Video",returnVisitVideoVariations:"Return Visit Video",memorialInvitationVideoVariations:"Memorial Invitation Video",initialCallVariations:"Initial Call",returnVisitVariations:"Return Visit",bibleStudyVariations:"Bible Study",talkVariations:"Talk",memorialInvitationVariations:"Memorial Invitation",assignmentAyfVariations:"{{ assignment }}: ({{ duration }} min.) {{ sourc

SyntaxError: Unexpected token *

**Comment by SnRoma5** [comment]
Is it complicated to change the modified version of version 1.36.0 [1.36.3](https://github.com/rhahao/jw-epub-parser/files/13285174/index.zip) so that it works for my application and the new workbook?

**Comment by rhahao** [comment]
Thanks! I will try to prepare or modify how the package gets compiled to solve this. Thanks for your patience.

**Comment by rhahao** [comment]
@SnRoma5: could you please try this file and see if it works? 
[index.cjs.zip](https://github.com/rhahao/jw-epub-parser/files/13294447/index.cjs.zip)

**Comment by rhahao** [comment]
I would like to ask as well if you’ve already tried the browser version before. (The edit to change import from require is still needed, at least for now). But if it works, I can create a commonJS output for the browser version.

I would like to know too the Electron version you are using to duplicate the issue on my end.

**Comment by rhahao** [comment]
@SnRoma5: Please disregard my 2 previous messages and try this one. I’ve already tested it on Electron 27.0.3 and it works fine.
[index.cjs.zip](https://github.com/rhahao/jw-epub-parser/files/13300352/index.cjs.zip)

**Comment by SnRoma5** [comment]
@rhahao You are the best! It works :) Thank you dear brother. I really appreciate your help!

I have a small problem. In the Italian workbook, sometimes the pipe symbol "|" is used in the title.
For example: 
english: 4. Interest in Others-What Jesus Did
Italian: 4. Interesse verso gli altri | Cosa fece Gesù

In your code, however, you use the "|" for split().
Could you use a different character?

I also wanted to ask if you could add Italian as well. I have already prepared it:
{
	"januaryVariations": "Gennaio",
	"februaryVariations": "Febbraio",
	"marchVariations": "Marzo",
	"aprilVariations": "Aprile",
	"mayVariations": "Maggio",
	"juneVariations": "Giugno",
	"julyVariations": "Luglio",
	"augustVariations": "Agosto",
	"septemberVariations": "Settembre",
	"octoberVariations": "Ottobre",
	"novemberVariations": "Novembre",
	"decemberVariations": "Dicembre",
	"studyArticleDateVariations": "Articolo di studio {{ number }} ({{ date }})",
	"partMinutesSeparatorVariations": "({{ duration }} min)"
}

**Comment by rhahao** [comment]
Happy to know that it works! 👍

And yes, I an going to change the separator to avoid issue you mentioned above, and will include the Italian data as well. It should be ready soon.

**Comment by rhahao** [comment]
@SnRoma5: new version released to fix this issue: https://github.com/sws2apps/jw-epub-parser/releases/tag/v3.6.0
Thank you!

**Comment by SnRoma5** [comment]
@rhahao Thank you very much! 💯
